DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Accounts;
DROP TABLE IF EXISTS Transactions;
DROP TABLE IF EXISTS InvestmentAccounts;
DROP TABLE IF EXISTS Roles;
DROP TABLE IF EXISTS UserRoles;
DROP TABLE IF EXISTS AccountTypes;
DROP TABLE IF EXISTS AUTO_INCREMENT;
